package org.omg.PortableServer;


/**
* org/omg/PortableServer/REQUEST_PROCESSING_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from d:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u40/2855/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, February 10, 2015 9:55:25 PM PST
*/

public interface REQUEST_PROCESSING_POLICY_ID
{

  /**
	 * The value representing REQUEST_PROCESSING_POLICY_ID.
	 */
  public static final int value = (int)(22L);
}
